name: Sinergia Capital
favicon: null
layout_spectrum: 0.691151705570519
typography_spectrum: 0.5755494316108525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.149598651798442
  lightness: 0.7495291172526777
  saturation: 0.14816518896259367
  rhythmicContrast: 0.5886046311352402
purpose: []
